// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7jZ5H_ky6YYVgAK_emTaferOEa_lMfGA',
    appId: '1:1092367710878:web:b26357b97d80632185598f',
    messagingSenderId: '1092367710878',
    projectId: 'thenews-everyday',
    authDomain: 'thenews-everyday.firebaseapp.com',
    storageBucket: 'thenews-everyday.appspot.com',
    measurementId: 'G-E6FT2E5VFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATdYyg8o3FT_7gFNuUBjRybZUJYhPqssk',
    appId: '1:1092367710878:android:a1ec0ef375f29ec385598f',
    messagingSenderId: '1092367710878',
    projectId: 'thenews-everyday',
    storageBucket: 'thenews-everyday.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeEW5iautagvAdr6gocHxRHvSEvK-jX-c',
    appId: '1:1092367710878:ios:b270dd1e7584be4785598f',
    messagingSenderId: '1092367710878',
    projectId: 'thenews-everyday',
    storageBucket: 'thenews-everyday.appspot.com',
    androidClientId: '1092367710878-03hjg4vuc14cg26qgn3fa4c122mcsro4.apps.googleusercontent.com',
    iosClientId: '1092367710878-bethnf5b95g5095t7eqku7mtkeo4eq4u.apps.googleusercontent.com',
    iosBundleId: 'com.caribbean.newsEveryday',
  );
}
